### ISSUE TITLE
Missing feeds

### ISSUE THREAD

**Issue by adamyonk** [markmichon/gatsby-plugin-feed-generator#17]
I'm suddenly seeing the feeds and feed links not being generated on gatsby 2.15.20 / gatsby-plugin-feed-generator 2.0.3, but I'm also not seeing any errors. My config looks like this:
```
    {
      resolve: "gatsby-plugin-feed-generator",
      options: {
        siteQuery: `
          {
            site {
              siteMetadata {
                title
                description
                siteUrl
                author
              }
            }
          }
        `,
        feeds: [
          {
            name: 'feed',
            query: `
              {
                allMarkdownRemark(
                  filter: { frontmatter: { templateKey: { eq: "post" }, published: { eq: true } } },
                  sort: { order: DESC, fields: [frontmatter___date] }
                ) {
                  edges {
                    node {
                      html
                      id
                      frontmatter {
                        date
                        path
                        title
                      }
                    }
                  }
                }
              }
            `,
            normalize: ({ query: { site, allMarkdownRemark } }) => {
              return allMarkdownRemark.edges.map(edge => {
                return {
                  title: edge.node.frontmatter.title,
                  date: edge.node.frontmatter.date,
                  url: site.siteMetadata.siteUrl + edge.node.frontmatter.path,
                  html: edge.node.html,
                }
              })
            },
          }
        ],
      },
    },
```

**Comment by markmichon** [comment]
Hi @adamyonk, I just did a trial on my gatsby site with the latest (2.15.22) and it is still working as expected. Maybe they broke something in the patch releases. (No changelog makes it hard to tell 😢)

Try updating and see if that fixes it.

**Comment by adamyonk** [comment]
Thanks for checking that out! I'm updating my site (https://github.com/adamyonk/adamyonk.com) from an older version (from before there were multiple feeds allowed in the config). I think I must have something else wrong with my config, I'll keep digging.

**Comment by markmichon** [comment]
@adamyonk Found the problem. In one of the recent updates I removed all the defaults, but left the docs as is. 
I'll push an update to either the docs or defaults in the next few days, but for now you can set `rss` and `json` to true in the options (see the readme for an example)

**Comment by adamyonk** [comment]
Aha, that was it! Thanks so much!
