### ISSUE TITLE
Is possible to add enclosure to the feed?

### ISSUE THREAD

**Issue by urre** [markmichon/gatsby-plugin-feed-generator#25]
Is possible to add enclosure to the feed?

**Comment by markmichon** [comment]
@urre, sorry this isn't maintained anymore. Not even sure if it works with modern gatsby. I'd suggest looking for a modern alternative or forking.

**Comment by urre** [comment]
@markmichon It works well on newest Gatsby actually. We use it for our feeds https://curity.io/feeds/. It was just enclosure that I'm missing for featured images in feedly/feedbin. No biggie.
