### ISSUE TITLE
Implement methods for non-markdown based feeds

### ISSUE THREAD

**Issue by markmichon** [markmichon/gatsby-plugin-feed-generator#3]
Currently the plugin relies heavily on the use and structure of allMarkdownRemark and it's graphql structure. It would be ideal if this could be abstracted out into the config to allow for other formats, and in the future combining multiple formats into a single feed.

**Comment by anithri** [comment]
Here's one possible solution #6

**Comment by markmichon** [comment]
Resolved through #11
