### ISSUE TITLE
`path.join` mangles schema-delimiting double-slash

### ISSUE THREAD

**Issue by coreyward** [markmichon/gatsby-plugin-feed-generator#5]
In a couple places in `gatsby-node` this is employed:

```js
path.join(siteUrl, slug),
```

If `siteUrl` is a fully qualified URL with a schema, such as `https://www.example.org/`, this has the undesirable effect of treating the schema-host separator as a path divider: 

```
// output => https:/www.example.org/[slug]
```

There are some other “url join” libraries out there; I resolved by doing the following instead:

```js
const url = {
  join: (...parts) => {
    let result = "" + parts.shift()
    parts.forEach(part => {
      const trailingSlashPresent = result.charAt(result.length - 1) == "/"
      const preceedingSlashPresent = part.charAt(0) == "/"

      if (trailingSlashPresent) {
        if (preceedingSlashPresent) {
          result = result + part.substr(1)
        } else {
          result = result + part
        }
      } else {
        if (preceedingSlashPresent) {
          result = result + part
        } else {
          result = result + "/" + part
        }
      }
    })

    return result;
  }
}
```

Then when referencing URLs: 

```js
url.join(siteUrl, "something", "/something-else")
```

**Comment by brandonweiss** [comment]
I just tried this plugin and I think I ran into this bug. My `siteUrl` is `"https://anti-pattern.com"` but the URL is mangled in two places (that I can see).

In the JSON feed the `feed_url` is `"https:/anti-pattern.com/feed.json/.json"`.

In the XML feed the `image.url` is `"https:/anti-pattern.com/image.png"`.

**Comment by markmichon** [comment]
@brandonweiss Any chance you could provide the config that is causing this?

**Comment by brandonweiss** [comment]
@markmichon Of course!

```javascript
siteMetadata: {
  author: "Brandon Weiss",
  description: "description",
  title: "Anti-pattern",
  siteUrl: "https://anti-pattern.com",
},
plugins: [
  {
    resolve: "gatsby-plugin-feed-generator",
    options: {
      rss: true,
      json: true,
      siteQuery: `
        {
          site {
            siteMetadata {
              author
              description
              title
              siteUrl
            }
          }
        }
      `,
      feeds: [
        {
          name: "feed",
          query: `
          {
            allMdx(sort: { fields: [frontmatter___date], order: DESC }) {
              edges {
                node {
                  html
                  fields {
                    slug
                  }
                  frontmatter {
                    date
                    title
                    description
                  }
                }
              }
            }
          }
        `,
          normalize: ({ query: { site, allMdx } }) => {
            return allMdx.edges.map(({ node: post }) => {
              return {
                date: post.frontmatter.date,
                html: post.html,
                title: post.frontmatter.title,
                url: site.siteMetadata.siteUrl + post.fields.slug,
              }
            })
          },
        },
      ],
    },
  },
],
```

I didn’t think to include it because it seemed like a standard/default config, but maybe there’s something unusual I’m doing.

**Comment by markmichon** [comment]
@brandonweiss Thanks! Yeah nothing looks out of the ordinary there. 

Should be resolved now. Let me know if you run into any issues. I couldn't duplicate it, but I suspect it had to do with trailing slashes. `2.0.1` handles that issue.

**Comment by brandonweiss** [comment]
@markmichon Thanks! The backslash issue seems to be fixed, although the extension on `feed_url` still seems to be doubled. It’s showing as `"https://anti-pattern.com/feed.json.json"`.

**Comment by brandonweiss** [comment]
Ah yeah, the extension is being added in two places.

https://github.com/markmichon/gatsby-plugin-feed-generator/blob/e60973b65f5c8c0c4172163f0d3ec8d04ee0aff0/src/gatsby-node.js#L23

https://github.com/markmichon/gatsby-plugin-feed-generator/blob/e60973b65f5c8c0c4172163f0d3ec8d04ee0aff0/src/utils.js#L16-L17

I’d normally open a PR but I’m not sure exactly where you’d prefer to do the appending.

**Comment by markmichon** [comment]
Alright. Latest release on npm has it taken care of. Thanks for keeping things in check 👍

**Comment by brandonweiss** [comment]
Thanks for fixing it so quickly! ❤️
